env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 2021
  parser: '@typescript-eslint/parser'
  sourceType: 'module'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  no-undef: 'off'
  vue/multi-word-component-names: 'off'
  vue/max-attributes-per-line: 'off'
  vue/singleline-html-element-content-newline: 'off'
  vue/html-self-closing: [error, html: { void: always }]
